name: unittests
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

  push:
    branches:
      - main

jobs:
  unittests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' , '3.11', '3.12', '3.13', '3.14' ]
        libraries-versions: [ 'pandas==1.5.2 "numpy<2.0"', 'pandas==2.2.2', 'pandas>=2.2.3', 'pandas>=2.3.3' ]
        exclude:
          - python-version: '3.13'
            libraries-versions: 'pandas==1.5.2 "numpy<2.0"'
          - python-version: '3.13'
            libraries-versions: 'pandas==2.2.2'
          - python-version: '3.14'
            libraries-versions: 'pandas==1.5.2 "numpy<2.0"'
          - python-version: '3.14'
            libraries-versions: 'pandas==2.2.2'
          - python-version: '3.14'
            libraries-versions: 'pandas>=2.2.3'
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ matrix.libraries-versions }}-${{ hashFiles('**/requirements.txt', '**/test-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ matrix.libraries-versions }}-
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      - name: Install dependencies ${{ matrix.python-version }}
        run: |
          REQS="-r requirements.txt -r test-requirements.txt"
          pip install --upgrade --upgrade-strategy eager ${REQS}
          pip install ${{ matrix.libraries-versions }}

      - name: Run tests
        run: |
          python -m pytest -vv

